version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    container_name: postgresdb
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
volumes:
  db:
